/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quay

// Information for creating a notification on a repository
type NotificationCreateRequest struct {
	// JSON config information for the specific event of notification
	EventConfig *interface{} `json:"eventConfig"`

	// The human-readable title of the notification
	Title string `json:"title,omitempty"`

	// JSON config information for the specific method of notification
	Config *interface{} `json:"config"`

	// The event on which the notification will respond
	Event string `json:"event"`

	// The method of notification (such as email or web callback)
	Method string `json:"method"`
}
