/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quay

type NewStarredRepository struct {
	// Namespace in which the repository belongs
	Namespace string `json:"namespace"`

	// Repository name
	Repository string `json:"repository"`
}
