/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quay

type ApiError struct {
	// Status code of the response.
	Status int32 `json:"status"`

	// Deprecated; alias for detail
	ErrorMessage string `json:"error_message,omitempty"`

	// Unique error code to identify the type of error.
	Title string `json:"title"`

	// Deprecated; alias for detail
	ErrorType string `json:"error_type,omitempty"`

	// Details about the specific instance of the error.
	Detail string `json:"detail,omitempty"`

	// Reference to the type of the error.
	Type_ string `json:"type"`
}
