/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quay

// Fields which can be updated in a user.
type UpdateUser struct {
	// The user's username
	Username string `json:"username,omitempty"`

	// The optional entered family name for the user
	FamilyName string `json:"family_name,omitempty"`

	// The optional entered given name for the user
	GivenName string `json:"given_name,omitempty"`

	// Whether the user desires to receive an invoice email.
	InvoiceEmail bool `json:"invoice_email,omitempty"`

	// The optional entered company for the user
	Company string `json:"company,omitempty"`

	// The user's password
	Password string `json:"password,omitempty"`

	// The user's email address
	Email string `json:"email,omitempty"`

	// The number of seconds for tag expiration
	TagExpirationS int32 `json:"tag_expiration_s,omitempty"`
}
