/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quay

// Description of a new repository
type NewRepo struct {
	// Namespace in which the repository should be created. If omitted, the username of the caller is used
	Namespace string `json:"namespace,omitempty"`

	// Visibility which the repository will start with
	Visibility string `json:"visibility"`

	// Repository name
	Repository string `json:"repository"`

	// Markdown encoded description for the repository
	Description string `json:"description"`
}
