/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quay

// Optional run parameters for activating the build trigger
type RunParameters struct {
	// (SCM only) If specified, the name of the branch to build.
	BranchName string `json:"branch_name,omitempty"`

	// (Custom Only) If specified, the ref/SHA1 used to checkout a git repository.
	CommitSha string `json:"commit_sha,omitempty"`
}
