/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quay

// Change the trust settings for the repository.
type ChangeRepoTrust struct {
	// Whether or not signing is enabled for the repository.
	TrustEnabled bool `json:"trust_enabled"`
}
