/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quay

// Restores a tag to a specific image
type RestoreTag struct {
	// Image identifier to which the tag should point
	Image string `json:"image"`

	// If specified, the manifest digest that should be used
	ManifestDigest string `json:"manifest_digest,omitempty"`
}
