---
swagger: "2.0"
info:
  description: "This API allows you to perform many of the operations required to\
    \ work with Quay repositories, users, and organizations. You can find out more\
    \ at <a href=\"https://quay.io\">Quay</a>."
  version: "v1"
  title: "Quay Frontend"
  termsOfService: "https://quay.io/tos"
  contact:
    email: "support@quay.io"
host: "quay.io"
basePath: "/"
tags:
- name: "billing"
  description: "Billing information, subscriptions, and plan information."
- name: "build"
  description: "Create, list, cancel and get status/logs of repository builds."
- name: "discovery"
  description: "API discovery information."
- name: "error"
  description: "Error details API"
- name: "globalmessages"
  description: "Messages API."
- name: "image"
  description: "List and lookup repository images."
- name: "logs"
  description: "Access usage logs for organizations or repositories."
- name: "manifest"
  description: "Manage the manifests of a repository."
- name: "organization"
  description: "Manage organizations, members and OAuth applications."
- name: "permission"
  description: "Manage repository permissions."
- name: "prototype"
  description: "Manage default permissions added to repositories."
- name: "repository"
  description: "List, create and manage repositories."
- name: "repositorynotification"
  description: "List, create and manage repository events/notifications."
- name: "repotoken"
  description: "Manage repository access tokens (DEPRECATED)."
- name: "robot"
  description: "Manage user and organization robot accounts."
- name: "search"
  description: "Conduct searches against all registry context."
- name: "secscan"
  description: "List and manage repository vulnerabilities and other security information."
- name: "signing"
  description: "List and manage repository signing information"
- name: "tag"
  description: "Manage the tags of a repository."
- name: "team"
  description: "Create, list and manage an organization's teams."
- name: "trigger"
  description: "Create, list and manage build triggers."
- name: "user"
  description: "Manage the current user."
- name: "userfiles"
  description: ""
schemes:
- "https"
paths:
  /api/v1/organization/{orgname}/invoices:
    get:
      tags:
      - "billing"
      description: "List the invoices for the specified orgnaization."
      operationId: "listOrgInvoices"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.billing.OrganizationInvoiceList"
    x-tag: "billing"
    x-path: "/api/v1/organization/{orgname}/invoices"
  /api/v1/plans/:
    get:
      tags:
      - "billing"
      description: "List the avaialble plans."
      operationId: "listPlans"
    x-name: "endpoints.api.billing.ListPlans"
    x-tag: "billing"
    x-path: "/api/v1/plans/"
  /api/v1/repository/{repository}/build/:
    get:
      tags:
      - "build"
      description: "Get the list of repository builds."
      operationId: "getRepoBuilds"
      security:
      - oauth2_implicit:
        - "repo:read"
    post:
      tags:
      - "build"
      description: "Request that a repository be built and pushed from the specified\
        \ input."
      operationId: "requestRepoBuild"
      security:
      - oauth2_implicit:
        - "repo:write"
    x-name: "endpoints.api.build.RepositoryBuildList"
    x-path: "/api/v1/repository/{repository}/build/"
    x-tag: "build"
  /api/v1/repository/{repository}/build/{build_uuid}/status:
    get:
      tags:
      - "build"
      description: "Return the status for the builds specified by the build uuids."
      operationId: "getRepoBuildStatus"
      security:
      - oauth2_implicit:
        - "repo:read"
    x-name: "endpoints.api.build.RepositoryBuildStatus"
    x-tag: "build"
    x-path: "/api/v1/repository/{repository}/build/{build_uuid}/status"
  /api/v1/repository/{repository}/build/{build_uuid}:
    get:
      tags:
      - "build"
      description: "Returns information about a build."
      operationId: "getRepoBuild"
      security:
      - oauth2_implicit:
        - "repo:read"
    delete:
      tags:
      - "build"
      description: "Cancels a repository build."
      operationId: "cancelRepoBuild"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.build.RepositoryBuildResource"
    x-path: "/api/v1/repository/{repository}/build/{build_uuid}"
    x-tag: "build"
  /api/v1/repository/{repository}/build/{build_uuid}/logs:
    get:
      tags:
      - "build"
      description: "Return the build logs for the build specified by the build uuid."
      operationId: "getRepoBuildLogs"
      security:
      - oauth2_implicit:
        - "repo:read"
    x-name: "endpoints.api.build.RepositoryBuildLogs"
    x-tag: "build"
    x-path: "/api/v1/repository/{repository}/build/{build_uuid}/logs"
  /api/v1/discovery:
    get:
      tags:
      - "discovery"
      description: "List all of the API endpoints available in the swagger API format."
      operationId: "discovery"
    x-name: "endpoints.api.discovery.DiscoveryResource"
    x-tag: "discovery"
    x-path: "/api/v1/discovery"
  /api/v1/error/{error_type}:
    get:
      tags:
      - "error"
      description: "Get a detailed description of the error"
      operationId: "getErrorDescription"
    x-name: "endpoints.api.error.Error"
    x-tag: "error"
    x-path: "/api/v1/error/{error_type}"
  /api/v1/messages:
    get:
      tags:
      - "globalmessages"
      description: "Return a super users messages"
      operationId: "getGlobalMessages"
    post:
      tags:
      - "globalmessages"
      description: "Create a message"
      operationId: "createGlobalMessage"
      security:
      - oauth2_implicit:
        - "super:user"
    x-name: "endpoints.api.globalmessages.GlobalUserMessages"
    x-tag: "globalmessages"
    x-path: "/api/v1/messages"
  /api/v1/repository/{repository}/image/{image_id}:
    get:
      tags:
      - "image"
      description: "Get the information available for the specified image."
      operationId: "getImage"
      security:
      - oauth2_implicit:
        - "repo:read"
    x-name: "endpoints.api.image.RepositoryImage"
    x-tag: "image"
    x-path: "/api/v1/repository/{repository}/image/{image_id}"
  /api/v1/repository/{repository}/image/:
    get:
      tags:
      - "image"
      description: "List the images for the specified repository."
      operationId: "listRepositoryImages"
      security:
      - oauth2_implicit:
        - "repo:read"
    x-name: "endpoints.api.image.RepositoryImageList"
    x-tag: "image"
    x-path: "/api/v1/repository/{repository}/image/"
  /api/v1/organization/{orgname}/aggregatelogs:
    get:
      tags:
      - "logs"
      description: "Gets the aggregated logs for the specified organization."
      operationId: "getAggregateOrgLogs"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.logs.OrgAggregateLogs"
    x-tag: "logs"
    x-path: "/api/v1/organization/{orgname}/aggregatelogs"
  /api/v1/organization/{orgname}/logs:
    get:
      tags:
      - "logs"
      description: "List the logs for the specified organization."
      operationId: "listOrgLogs"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.logs.OrgLogs"
    x-tag: "logs"
    x-path: "/api/v1/organization/{orgname}/logs"
  /api/v1/repository/{repository}/logs:
    get:
      tags:
      - "logs"
      description: "List the logs for the specified repository."
      operationId: "listRepoLogs"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.logs.RepositoryLogs"
    x-tag: "logs"
    x-path: "/api/v1/repository/{repository}/logs"
  /api/v1/user/logs:
    get:
      tags:
      - "logs"
      description: "List the logs for the current user."
      operationId: "listUserLogs"
      security:
      - oauth2_implicit:
        - "user:admin"
    x-name: "endpoints.api.logs.UserLogs"
    x-tag: "logs"
    x-path: "/api/v1/user/logs"
  /api/v1/user/aggregatelogs:
    get:
      tags:
      - "logs"
      description: "Returns the aggregated logs for the current user."
      operationId: "getAggregateUserLogs"
      security:
      - oauth2_implicit:
        - "user:admin"
    x-name: "endpoints.api.logs.UserAggregateLogs"
    x-tag: "logs"
    x-path: "/api/v1/user/aggregatelogs"
  /api/v1/repository/{repository}/aggregatelogs:
    get:
      tags:
      - "logs"
      description: "Returns the aggregated logs for the specified repository."
      operationId: "getAggregateRepoLogs"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.logs.RepositoryAggregateLogs"
    x-tag: "logs"
    x-path: "/api/v1/repository/{repository}/aggregatelogs"
  /api/v1/repository/{repository}/manifest/{manifestref}/labels:
    get:
      tags:
      - "manifest"
      description: ""
      operationId: "listManifestLabels"
      security:
      - oauth2_implicit:
        - "repo:read"
    post:
      tags:
      - "manifest"
      description: "Adds a new label into the tag manifest."
      operationId: "addManifestLabel"
      security:
      - oauth2_implicit:
        - "repo:write"
    x-name: "endpoints.api.manifest.RepositoryManifestLabels"
    x-path: "/api/v1/repository/{repository}/manifest/{manifestref}/labels"
    x-tag: "manifest"
  /api/v1/repository/{repository}/manifest/{manifestref}/labels/{labelid}:
    get:
      tags:
      - "manifest"
      description: "Retrieves the label with the specific ID under the manifest."
      operationId: "getManifestLabel"
      security:
      - oauth2_implicit:
        - "repo:read"
    delete:
      tags:
      - "manifest"
      description: "Deletes an existing label from a manifest."
      operationId: "deleteManifestLabel"
      security:
      - oauth2_implicit:
        - "repo:write"
    x-name: "endpoints.api.manifest.ManageRepositoryManifestLabel"
    x-path: "/api/v1/repository/{repository}/manifest/{manifestref}/labels/{labelid}"
    x-tag: "manifest"
  /api/v1/organization/{orgname}/members/{membername}:
    get:
      tags:
      - "organization"
      description: "Retrieves the details of a member of the organization."
      operationId: "getOrganizationMember"
      security:
      - oauth2_implicit:
        - "org:admin"
    delete:
      tags:
      - "organization"
      description: "Removes a member from an organization, revoking all its repository\n\
        \        priviledges and removing it from all teams in the organization."
      operationId: "removeOrganizationMember"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.organization.OrganizationMember"
    x-path: "/api/v1/organization/{orgname}/members/{membername}"
    x-tag: "organization"
  /api/v1/organization/{orgname}:
    get:
      tags:
      - "organization"
      description: "Get the details for the specified organization"
      operationId: "getOrganization"
    put:
      tags:
      - "organization"
      description: "Change the details for the specified organization."
      operationId: "changeOrganizationDetails"
      security:
      - oauth2_implicit:
        - "org:admin"
    delete:
      tags:
      - "organization"
      description: "Deletes the specified organization."
      operationId: "deleteAdminedOrganization"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.organization.Organization"
    x-path: "/api/v1/organization/{orgname}"
    x-tag: "organization"
  /api/v1/organization/{orgname}/applications/{client_id}:
    get:
      tags:
      - "organization"
      description: "Retrieves the application with the specified client_id under the\
        \ specified organization"
      operationId: "getOrganizationApplication"
      security:
      - oauth2_implicit:
        - "org:admin"
    put:
      tags:
      - "organization"
      description: "Updates an application under this organization."
      operationId: "updateOrganizationApplication"
      security:
      - oauth2_implicit:
        - "org:admin"
    delete:
      tags:
      - "organization"
      description: "Deletes the application under this organization."
      operationId: "deleteOrganizationApplication"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.organization.OrganizationApplicationResource"
    x-path: "/api/v1/organization/{orgname}/applications/{client_id}"
    x-tag: "organization"
  /api/v1/organization/:
    post:
      tags:
      - "organization"
      description: "Create a new organization."
      operationId: "createOrganization"
      security:
      - oauth2_implicit:
        - "user:admin"
    x-name: "endpoints.api.organization.OrganizationList"
    x-tag: "organization"
    x-path: "/api/v1/organization/"
  /api/v1/app/{client_id}:
    get:
      tags:
      - "organization"
      description: "Get information on the specified application."
      operationId: "getApplicationInformation"
    x-name: "endpoints.api.organization.ApplicationInformation"
    x-tag: "organization"
    x-path: "/api/v1/app/{client_id}"
  /api/v1/organization/{orgname}/applications:
    get:
      tags:
      - "organization"
      description: "List the applications for the specified organization"
      operationId: "getOrganizationApplications"
      security:
      - oauth2_implicit:
        - "org:admin"
    post:
      tags:
      - "organization"
      description: "Creates a new application under this organization."
      operationId: "createOrganizationApplication"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.organization.OrganizationApplications"
    x-path: "/api/v1/organization/{orgname}/applications"
    x-tag: "organization"
  /api/v1/organization/{orgname}/members:
    get:
      tags:
      - "organization"
      description: "List the human members of the specified organization."
      operationId: "getOrganizationMembers"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.organization.OrganizationMemberList"
    x-tag: "organization"
    x-path: "/api/v1/organization/{orgname}/members"
  /api/v1/repository/{repository}/permissions/user/:
    get:
      tags:
      - "permission"
      description: "List all user permissions."
      operationId: "listRepoUserPermissions"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.permission.RepositoryUserPermissionList"
    x-tag: "permission"
    x-path: "/api/v1/repository/{repository}/permissions/user/"
  /api/v1/repository/{repository}/permissions/team/:
    get:
      tags:
      - "permission"
      description: "List all team permission."
      operationId: "listRepoTeamPermissions"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.permission.RepositoryTeamPermissionList"
    x-tag: "permission"
    x-path: "/api/v1/repository/{repository}/permissions/team/"
  /api/v1/repository/{repository}/permissions/team/{teamname}:
    get:
      tags:
      - "permission"
      description: "Fetch the permission for the specified team."
      operationId: "getTeamPermissions"
      security:
      - oauth2_implicit:
        - "repo:admin"
    put:
      tags:
      - "permission"
      description: "Update the existing team permission."
      operationId: "changeTeamPermissions"
      security:
      - oauth2_implicit:
        - "repo:admin"
    delete:
      tags:
      - "permission"
      description: "Delete the permission for the specified team."
      operationId: "deleteTeamPermissions"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.permission.RepositoryTeamPermission"
    x-path: "/api/v1/repository/{repository}/permissions/team/{teamname}"
    x-tag: "permission"
  /api/v1/repository/{repository}/permissions/user/{username}:
    get:
      tags:
      - "permission"
      description: "Get the permission for the specified user."
      operationId: "getUserPermissions"
      security:
      - oauth2_implicit:
        - "repo:admin"
    put:
      tags:
      - "permission"
      description: "Update the perimssions for an existing repository."
      operationId: "changeUserPermissions"
      security:
      - oauth2_implicit:
        - "repo:admin"
    delete:
      tags:
      - "permission"
      description: "Delete the permission for the user."
      operationId: "deleteUserPermissions"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.permission.RepositoryUserPermission"
    x-path: "/api/v1/repository/{repository}/permissions/user/{username}"
    x-tag: "permission"
  /api/v1/repository/{repository}/permissions/user/{username}/transitive:
    get:
      tags:
      - "permission"
      description: "Get the fetch the permission for the specified user."
      operationId: "getUserTransitivePermission"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.permission.RepositoryUserTransitivePermission"
    x-tag: "permission"
    x-path: "/api/v1/repository/{repository}/permissions/user/{username}/transitive"
  /api/v1/organization/{orgname}/prototypes:
    get:
      tags:
      - "prototype"
      description: "List the existing prototypes for this organization."
      operationId: "getOrganizationPrototypePermissions"
      security:
      - oauth2_implicit:
        - "org:admin"
    post:
      tags:
      - "prototype"
      description: "Create a new permission prototype."
      operationId: "createOrganizationPrototypePermission"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.prototype.PermissionPrototypeList"
    x-path: "/api/v1/organization/{orgname}/prototypes"
    x-tag: "prototype"
  /api/v1/organization/{orgname}/prototypes/{prototypeid}:
    put:
      tags:
      - "prototype"
      description: "Update the role of an existing permission prototype."
      operationId: "updateOrganizationPrototypePermission"
      security:
      - oauth2_implicit:
        - "org:admin"
    delete:
      tags:
      - "prototype"
      description: "Delete an existing permission prototype."
      operationId: "deleteOrganizationPrototypePermission"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.prototype.PermissionPrototype"
    x-path: "/api/v1/organization/{orgname}/prototypes/{prototypeid}"
    x-tag: "prototype"
  /api/v1/repository:
    get:
      tags:
      - "repository"
      description: "Fetch the list of repositories visible to the current user under\
        \ a variety of situations."
      operationId: "listRepos"
      security:
      - oauth2_implicit:
        - "repo:read"
    post:
      tags:
      - "repository"
      description: "Create a new repository."
      operationId: "createRepo"
      security:
      - oauth2_implicit:
        - "repo:create"
    x-name: "endpoints.api.repository.RepositoryList"
    x-tag: "repository"
    x-path: "/api/v1/repository"
  /api/v1/repository/{repository}/changevisibility:
    post:
      tags:
      - "repository"
      description: "Change the visibility of a repository."
      operationId: "changeRepoVisibility"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.repository.RepositoryVisibility"
    x-tag: "repository"
    x-path: "/api/v1/repository/{repository}/changevisibility"
  /api/v1/repository/{repository}:
    get:
      tags:
      - "repository"
      description: "Fetch the specified repository."
      operationId: "getRepo"
      security:
      - oauth2_implicit:
        - "repo:read"
    put:
      tags:
      - "repository"
      description: "Update the description in the specified repository."
      operationId: "updateRepo"
      security:
      - oauth2_implicit:
        - "repo:write"
    delete:
      tags:
      - "repository"
      description: "Delete a repository."
      operationId: "deleteRepository"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.repository.Repository"
    x-path: "/api/v1/repository/{repository}"
    x-tag: "repository"
  /api/v1/repository/{repository}/changetrust:
    post:
      tags:
      - "repository"
      description: "Change the visibility of a repository."
      operationId: "changeRepoTrust"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.repository.RepositoryTrust"
    x-tag: "repository"
    x-path: "/api/v1/repository/{repository}/changetrust"
  /api/v1/repository/{repository}/notification/{uuid}/test:
    post:
      tags:
      - "repositorynotification"
      description: "Queues a test notification for this repository."
      operationId: "testRepoNotification"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.repositorynotification.TestRepositoryNotification"
    x-tag: "repositorynotification"
    x-path: "/api/v1/repository/{repository}/notification/{uuid}/test"
  /api/v1/repository/{repository}/notification/:
    get:
      tags:
      - "repositorynotification"
      description: "List the notifications for the specified repository."
      operationId: "listRepoNotifications"
      security:
      - oauth2_implicit:
        - "repo:admin"
    post:
      tags:
      - "repositorynotification"
      description: ""
      operationId: "createRepoNotification"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.repositorynotification.RepositoryNotificationList"
    x-path: "/api/v1/repository/{repository}/notification/"
    x-tag: "repositorynotification"
  /api/v1/repository/{repository}/notification/{uuid}:
    get:
      tags:
      - "repositorynotification"
      description: "Get information for the specified notification."
      operationId: "getRepoNotification"
      security:
      - oauth2_implicit:
        - "repo:admin"
    post:
      tags:
      - "repositorynotification"
      description: "Resets repository notification to 0 failures."
      operationId: "resetRepositoryNotificationFailures"
      security:
      - oauth2_implicit:
        - "repo:admin"
    delete:
      tags:
      - "repositorynotification"
      description: "Deletes the specified notification."
      operationId: "deleteRepoNotification"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.repositorynotification.RepositoryNotification"
    x-path: "/api/v1/repository/{repository}/notification/{uuid}"
    x-tag: "repositorynotification"
  /api/v1/repository/{repository}/tokens/:
    get:
      tags:
      - "repotoken"
      description: "List the tokens for the specified repository."
      operationId: "listRepoTokens"
      security:
      - oauth2_implicit:
        - "repo:admin"
    post:
      tags:
      - "repotoken"
      description: "Create a new repository token."
      operationId: "createToken"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.repotoken.RepositoryTokenList"
    x-path: "/api/v1/repository/{repository}/tokens/"
    x-tag: "repotoken"
  /api/v1/repository/{repository}/tokens/{code}:
    get:
      tags:
      - "repotoken"
      description: "Fetch the specified repository token information."
      operationId: "getTokens"
      security:
      - oauth2_implicit:
        - "repo:admin"
    put:
      tags:
      - "repotoken"
      description: "Update the permissions for the specified repository token."
      operationId: "changeToken"
      security:
      - oauth2_implicit:
        - "repo:admin"
    delete:
      tags:
      - "repotoken"
      description: "Delete the repository token."
      operationId: "deleteToken"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.repotoken.RepositoryToken"
    x-path: "/api/v1/repository/{repository}/tokens/{code}"
    x-tag: "repotoken"
  /api/v1/user/robots:
    get:
      tags:
      - "robot"
      description: "List the available robots for the user."
      operationId: "getUserRobots"
      security:
      - oauth2_implicit:
        - "user:admin"
    x-name: "endpoints.api.robot.UserRobotList"
    x-tag: "robot"
    x-path: "/api/v1/user/robots"
  /api/v1/organization/{orgname}/robots/{robot_shortname}/permissions:
    get:
      tags:
      - "robot"
      description: "Returns the list of repository permissions for the org's robot."
      operationId: "getOrgRobotPermissions"
      security:
      - oauth2_implicit:
        - "user:admin"
    x-name: "endpoints.api.robot.OrgRobotPermissions"
    x-tag: "robot"
    x-path: "/api/v1/organization/{orgname}/robots/{robot_shortname}/permissions"
  /api/v1/organization/{orgname}/robots/{robot_shortname}/regenerate:
    post:
      tags:
      - "robot"
      description: "Regenerates the token for an organization robot."
      operationId: "regenerateOrgRobotToken"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.robot.RegenerateOrgRobot"
    x-tag: "robot"
    x-path: "/api/v1/organization/{orgname}/robots/{robot_shortname}/regenerate"
  /api/v1/organization/{orgname}/robots:
    get:
      tags:
      - "robot"
      description: "List the organization's robots."
      operationId: "getOrgRobots"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.robot.OrgRobotList"
    x-tag: "robot"
    x-path: "/api/v1/organization/{orgname}/robots"
  /api/v1/user/robots/{robot_shortname}/permissions:
    get:
      tags:
      - "robot"
      description: "Returns the list of repository permissions for the user's robot."
      operationId: "getUserRobotPermissions"
      security:
      - oauth2_implicit:
        - "user:admin"
    x-name: "endpoints.api.robot.UserRobotPermissions"
    x-tag: "robot"
    x-path: "/api/v1/user/robots/{robot_shortname}/permissions"
  /api/v1/user/robots/{robot_shortname}/regenerate:
    post:
      tags:
      - "robot"
      description: "Regenerates the token for a user's robot."
      operationId: "regenerateUserRobotToken"
      security:
      - oauth2_implicit:
        - "user:admin"
    x-name: "endpoints.api.robot.RegenerateUserRobot"
    x-tag: "robot"
    x-path: "/api/v1/user/robots/{robot_shortname}/regenerate"
  /api/v1/organization/{orgname}/robots/{robot_shortname}:
    get:
      tags:
      - "robot"
      description: "Returns the organization's robot with the specified name."
      operationId: "getOrgRobot"
      security:
      - oauth2_implicit:
        - "org:admin"
    put:
      tags:
      - "robot"
      description: "Create a new robot in the organization."
      operationId: "createOrgRobot"
      security:
      - oauth2_implicit:
        - "org:admin"
    delete:
      tags:
      - "robot"
      description: "Delete an existing organization robot."
      operationId: "deleteOrgRobot"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.robot.OrgRobot"
    x-path: "/api/v1/organization/{orgname}/robots/{robot_shortname}"
    x-tag: "robot"
  /api/v1/user/robots/{robot_shortname}:
    get:
      tags:
      - "robot"
      description: "Returns the user's robot with the specified name."
      operationId: "getUserRobot"
      security:
      - oauth2_implicit:
        - "user:admin"
    put:
      tags:
      - "robot"
      description: "Create a new user robot with the specified name."
      operationId: "createUserRobot"
      security:
      - oauth2_implicit:
        - "user:admin"
    delete:
      tags:
      - "robot"
      description: "Delete an existing robot."
      operationId: "deleteUserRobot"
      security:
      - oauth2_implicit:
        - "user:admin"
    x-name: "endpoints.api.robot.UserRobot"
    x-path: "/api/v1/user/robots/{robot_shortname}"
    x-tag: "robot"
  /api/v1/find/all:
    get:
      tags:
      - "search"
      description: "Get a list of entities and resources that match the specified\
        \ query."
      operationId: "conductSearch"
      security:
      - oauth2_implicit:
        - "repo:read"
    x-name: "endpoints.api.search.ConductSearch"
    x-tag: "search"
    x-path: "/api/v1/find/all"
  /api/v1/find/repositories:
    get:
      tags:
      - "search"
      description: "Get a list of apps and repositories that match the specified query."
      operationId: "conductRepoSearch"
    x-name: "endpoints.api.search.ConductRepositorySearch"
    x-tag: "search"
    x-path: "/api/v1/find/repositories"
  /api/v1/entities/{prefix}:
    get:
      tags:
      - "search"
      description: "Get a list of entities that match the specified prefix."
      operationId: "getMatchingEntities"
    x-name: "endpoints.api.search.EntitySearch"
    x-tag: "search"
    x-path: "/api/v1/entities/{prefix}"
  /api/v1/repository/{repository}/manifest/{manifestref}/security:
    get:
      tags:
      - "secscan"
      description: ""
      operationId: "getRepoManifestSecurity"
      security:
      - oauth2_implicit:
        - "repo:read"
    x-name: "endpoints.api.secscan.RepositoryManifestSecurity"
    x-tag: "secscan"
    x-path: "/api/v1/repository/{repository}/manifest/{manifestref}/security"
  /api/v1/repository/{repository}/image/{imageid}/security:
    get:
      tags:
      - "secscan"
      description: "Fetches the features and vulnerabilities (if any) for a repository\
        \ image."
      operationId: "getRepoImageSecurity"
      security:
      - oauth2_implicit:
        - "repo:read"
    x-name: "endpoints.api.secscan.RepositoryImageSecurity"
    x-tag: "secscan"
    x-path: "/api/v1/repository/{repository}/image/{imageid}/security"
  /api/v1/repository/{repository}/signatures:
    get:
      tags:
      - "signing"
      description: "Fetches the list of signed tags for the repository."
      operationId: "getRepoSignatures"
      security:
      - oauth2_implicit:
        - "repo:read"
    x-name: "endpoints.api.signing.RepositorySignatures"
    x-tag: "signing"
    x-path: "/api/v1/repository/{repository}/signatures"
  /api/v1/repository/{repository}/tag/{tag}/images:
    get:
      tags:
      - "tag"
      description: "List the images for the specified repository tag."
      operationId: "listTagImages"
      security:
      - oauth2_implicit:
        - "repo:read"
    x-name: "endpoints.api.tag.RepositoryTagImages"
    x-tag: "tag"
    x-path: "/api/v1/repository/{repository}/tag/{tag}/images"
  /api/v1/repository/{repository}/tag/{tag}/restore:
    post:
      tags:
      - "tag"
      description: "Restores a repository tag back to a previous image in the repository."
      operationId: "restoreTag"
      security:
      - oauth2_implicit:
        - "repo:write"
    x-name: "endpoints.api.tag.RestoreTag"
    x-tag: "tag"
    x-path: "/api/v1/repository/{repository}/tag/{tag}/restore"
  /api/v1/repository/{repository}/tag/{tag}:
    put:
      tags:
      - "tag"
      description: "Change which image a tag points to or create a new tag."
      operationId: "changeTag"
      security:
      - oauth2_implicit:
        - "repo:write"
    delete:
      tags:
      - "tag"
      description: "Delete the specified repository tag."
      operationId: "deleteFullTag"
      security:
      - oauth2_implicit:
        - "repo:write"
    x-name: "endpoints.api.tag.RepositoryTag"
    x-path: "/api/v1/repository/{repository}/tag/{tag}"
    x-tag: "tag"
  /api/v1/repository/{repository}/tag/:
    get:
      tags:
      - "tag"
      description: ""
      operationId: "listRepoTags"
      security:
      - oauth2_implicit:
        - "repo:read"
    x-name: "endpoints.api.tag.ListRepositoryTags"
    x-tag: "tag"
    x-path: "/api/v1/repository/{repository}/tag/"
  /api/v1/organization/{orgname}/team/{teamname}/members:
    get:
      tags:
      - "team"
      description: "Retrieve the list of members for the specified team."
      operationId: "getOrganizationTeamMembers"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.team.TeamMemberList"
    x-tag: "team"
    x-path: "/api/v1/organization/{orgname}/team/{teamname}/members"
  /api/v1/organization/{orgname}/team/{teamname}/permissions:
    get:
      tags:
      - "team"
      description: "Returns the list of repository permissions for the org's team."
      operationId: "getOrganizationTeamPermissions"
    x-name: "endpoints.api.team.TeamPermissions"
    x-tag: "team"
    x-path: "/api/v1/organization/{orgname}/team/{teamname}/permissions"
  /api/v1/organization/{orgname}/team/{teamname}/invite/{email}:
    put:
      tags:
      - "team"
      description: "Invites an email address to an existing team."
      operationId: "inviteTeamMemberEmail"
      security:
      - oauth2_implicit:
        - "org:admin"
    delete:
      tags:
      - "team"
      description: "Delete an invite of an email address to join a team."
      operationId: "deleteTeamMemberEmailInvite"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.team.InviteTeamMember"
    x-tag: "team"
    x-path: "/api/v1/organization/{orgname}/team/{teamname}/invite/{email}"
  /api/v1/organization/{orgname}/team/{teamname}:
    put:
      tags:
      - "team"
      description: "Update the org-wide permission for the specified team."
      operationId: "updateOrganizationTeam"
      security:
      - oauth2_implicit:
        - "org:admin"
    delete:
      tags:
      - "team"
      description: "Delete the specified team."
      operationId: "deleteOrganizationTeam"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.team.OrganizationTeam"
    x-path: "/api/v1/organization/{orgname}/team/{teamname}"
    x-tag: "team"
  /api/v1/organization/{orgname}/team/{teamname}/members/{membername}:
    put:
      tags:
      - "team"
      description: "Adds or invites a member to an existing team."
      operationId: "updateOrganizationTeamMember"
      security:
      - oauth2_implicit:
        - "org:admin"
    delete:
      tags:
      - "team"
      description: "Delete a member of a team. If the user is merely invited to join\n\
        \        the team, then the invite is removed instead."
      operationId: "deleteOrganizationTeamMember"
      security:
      - oauth2_implicit:
        - "org:admin"
    x-name: "endpoints.api.team.TeamMember"
    x-path: "/api/v1/organization/{orgname}/team/{teamname}/members/{membername}"
    x-tag: "team"
  /api/v1/repository/{repository}/trigger/:
    get:
      tags:
      - "trigger"
      description: "List the triggers for the specified repository."
      operationId: "listBuildTriggers"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.trigger.BuildTriggerList"
    x-tag: "trigger"
    x-path: "/api/v1/repository/{repository}/trigger/"
  /api/v1/repository/{repository}/trigger/{trigger_uuid}/activate:
    post:
      tags:
      - "trigger"
      description: "Activate the specified build trigger."
      operationId: "activateBuildTrigger"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.trigger.BuildTriggerActivate"
    x-tag: "trigger"
    x-path: "/api/v1/repository/{repository}/trigger/{trigger_uuid}/activate"
  /api/v1/repository/{repository}/trigger/{trigger_uuid}/start:
    post:
      tags:
      - "trigger"
      description: "Manually start a build from the specified trigger."
      operationId: "manuallyStartBuildTrigger"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.trigger.ActivateBuildTrigger"
    x-tag: "trigger"
    x-path: "/api/v1/repository/{repository}/trigger/{trigger_uuid}/start"
  /api/v1/repository/{repository}/trigger/{trigger_uuid}/builds:
    get:
      tags:
      - "trigger"
      description: "List the builds started by the specified trigger."
      operationId: "listTriggerRecentBuilds"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.trigger.TriggerBuildList"
    x-tag: "trigger"
    x-path: "/api/v1/repository/{repository}/trigger/{trigger_uuid}/builds"
  /api/v1/repository/{repository}/trigger/{trigger_uuid}:
    get:
      tags:
      - "trigger"
      description: "Get information for the specified build trigger."
      operationId: "getBuildTrigger"
      security:
      - oauth2_implicit:
        - "repo:admin"
    delete:
      tags:
      - "trigger"
      description: "Delete the specified build trigger."
      operationId: "deleteBuildTrigger"
      security:
      - oauth2_implicit:
        - "repo:admin"
    x-name: "endpoints.api.trigger.BuildTrigger"
    x-path: "/api/v1/repository/{repository}/trigger/{trigger_uuid}"
    x-tag: "trigger"
  /api/v1/user/:
    get:
      tags:
      - "user"
      description: "Get user information for the authenticated user."
      operationId: "getLoggedInUser"
      security:
      - oauth2_implicit:
        - "user:read"
    x-name: "endpoints.api.user.User"
    x-tag: "user"
    x-path: "/api/v1/user/"
  /api/v1/users/{username}:
    get:
      tags:
      - "user"
      description: "Get user information for the specified user."
      operationId: "getUserInformation"
    x-name: "endpoints.api.user.Users"
    x-tag: "user"
    x-path: "/api/v1/users/{username}"
  /api/v1/user/starred:
    get:
      tags:
      - "user"
      description: "List all starred repositories."
      operationId: "listStarredRepos"
      security:
      - oauth2_implicit:
        - "user:admin"
    post:
      tags:
      - "user"
      description: "Star a repository."
      operationId: "createStar"
      security:
      - oauth2_implicit:
        - "repo:read"
    x-name: "endpoints.api.user.StarredRepositoryList"
    x-tag: "user"
    x-path: "/api/v1/user/starred"
  /api/v1/user/starred/{repository}:
    delete:
      tags:
      - "user"
      description: "Removes a star from a repository."
      operationId: "deleteStar"
      security:
      - oauth2_implicit:
        - "user:admin"
    x-name: "endpoints.api.user.StarredRepository"
    x-tag: "user"
    x-path: "/api/v1/user/starred/{repository}"
  /userfiles/{file_id}:
    x-name: "data.userfiles.UserfilesHandlers"
    x-tag: "userfiles"
    x-path: "/userfiles/{file_id}"
securityDefinitions:
  oauth2_implicit:
    type: "oauth2"
    authorizationUrl: "https://quay.io/oauth/authorize"
    flow: "implicit"
    scopes:
      repo:write: "This application will be able to view, push and pull to all repositories\
        \ to which the granting user or robot account has write access"
      repo:read: "This application will be able to view and pull all repositories\
        \ visible to the granting user or robot account"
      repo:create: "This application will be able to create repositories in to any\
        \ namespaces that the granting user or robot account is allowed to create\
        \ repositories"
      repo:admin: "This application will have administrator access to all repositories\
        \ to which the granting user or robot account has access"
      user:admin: "This application will be able to administer your account including\
        \ creating robots and granting them permissions to your repositories. You\
        \ should have absolute trust in the requesting application before granting\
        \ this permission."
      org:admin: "This application will be able to administer your organizations including\
        \ creating robots, creating teams, adjusting team membership, and changing\
        \ billing settings. You should have absolute trust in the requesting application\
        \ before granting this permission."
      user:read: "This application will be able to read user information such as username\
        \ and email address."